In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [9]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_train)    #Standardising
X_train_scld = scaler.transform(X_train)

scaler_test = preprocessing.StandardScaler().fit(X_test)    #Standardising
X_test_scld = scaler.transform(X_test)
lr = LogisticRegression()
lr.fit(X_train_scld, y_train)
lr.score(X_test_scld, y_test)

0.9740740740740741

In [10]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9814814814814815

In [11]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

## Visualising KFold with a simple list and 3 Fold split

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


## Creating a basic function to get a score from any train test set and any model

In [13]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits = 3)

In [18]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    scaler = preprocessing.StandardScaler().fit(X_train)    #Standardising
    X_train_scld = scaler.transform(X_train)

    scaler_test = preprocessing.StandardScaler().fit(X_test)    #Standardising
    X_test_scld = scaler.transform(X_test)
    
    scores_lr.append(get_score(LogisticRegression(), X_train_scld, X_test_scld, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [19]:
print(scores_lr)
print(scores_svm)
print(scores_rf)

[0.9265442404006677, 0.9415692821368948, 0.9265442404006677]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
[0.9348914858096828, 0.9565943238731218, 0.9282136894824707]
