In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [18]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_train)    #Standardising
X_train_scld = scaler.transform(X_train)

scaler_test = preprocessing.StandardScaler().fit(X_test)    #Standardising
X_test_scld = scaler.transform(X_test)
lr = LogisticRegression()
lr.fit(X_train_scld, y_train)
lr.score(X_test_scld, y_test)

0.9629629629629629

In [16]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

In [17]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

## Visualising KFold with a simple list and 3 Fold split

In [1]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
for X_train, X_test in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(X_train, X_test)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]
